from os import getenv

FLASK_APP = getenv("FLASK_APP")
SQLALCHEMY_DATABASE_URI = getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False
SESSION_COOKIE_SECURE = getenv("SESSION_COOKIE_SECURE")
