RENTAL_METHODS = [
    "KEY",
    "CREDITCARD",
    "PAYPASS",
    "APPLEPAY",
    "ANDROIDPAY",
    "TRANSITCARD",
    "ACCOUNTNUMBER",
    "PHONE",
]
SYSTEM_ALERT_TYPE = [
    "SYSTEM_CLOSURE",
    "STATION_CLOSURE",
    "STATION_MOVE",
    "OTHER",
]
DURATION_EXECUTION =  100 #3600
FREE_BIKE_URL = ""
STATION_STATUS_URL = ""
